osx_image: xcode7

language: objective-c

# before_install:
# - brew update
# - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
- xcodebuild clean build -workspace JSQActivityKit.xcworkspace -scheme Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xcodebuild clean build test -project JSQActivityKit/JSQActivityKit.xcodeproj -scheme JSQActivityKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
